inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: "3"
  NewCops: enable

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/sidekiq-datadog.rb

Style/Documentation:
  Enabled: false
