name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.2", "3.3"]
        gemfile: [ Gemfile ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rspec
